# https://github.com/rolldown/rolldown/blob/37f7e886d265213ed6e14cfd434bad8c9642720a/.cargo/config.toml#L8
[target.'cfg(target_vendor = "apple")']
rustflags = ["-C", "link-args=-Wl,-undefined,dynamic_lookup,-no_fixup_chains"]
